argocd_repo: "vajrapu-srikanth04/argocd-manifests"

argocd_services: |
  applications|frontend|frontend-dev.yaml

keda_files: |
  vajrapu-srikanth04/stacks|non-prod/az-argocd-app-np1/frontend-keda.yaml
